version: "3.9"
services: 
    web:
        build: .
        ports: 
            - "11000:11000"
        volumes: 
            - ".:/app"
        depends_on: 
            - "redis"
            - "elasticsearch"
    redis:
        image: "redis:latest"
        ports: 
            - "6379:6379"
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.14.0"
        ports:
            - "9200:9200"
            - "9300:9300"
        environment: 
            - "discovery.type=single-node"
        